server:
  port: 80

spring:
  application:
    name: nacos-cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://192.168.8.4:3307/data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.4:8848
#    zookeeper:
#      connect-string: 192.168.8.4:2181

# 消费者将要去访问的微服务名称
servise-url:
  nacos-user-service: http://nacos-cloud-payment-service

mybatis-plus:
  type-aliases-package: com.jinliang.entity
  mapper-locations: classpath:mapper/*.xml

mybatis-plus-father-package: com.yejinliang.it

# Swagger配置
swagger-path: http://localhost:80/