server:
  port: 80

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://43.129.231.24:3307/data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
mybatis-plus:
  type-aliases-package: com.jinliang.entity
  mapper-locations: classpath:mapper/*.xml

mybatis-plus-father-package: com.yejinliang.it

# Swagger配置
swagger-path: http://localhost:80/